import type { Metadata } from "next";
import { Cousine } from "next/font/google";
import "./globals.css";


const cousine = Cousine({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-cousine",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${cousine.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
